Repository mercadopago/devsite-docs, pull requests merged in 2021-12, with the labels that each got.

#1384 Nueva documentación de VTEX
  guides/plugins/unofficial/vtex.en.md
  guides/plugins/unofficial/vtex.es.md
  guides/plugins/unofficial/vtex.pt.md
  guides/plugins/unofficial/vtex/common-errors.en.md
  guides/plugins/unofficial/vtex/common-errors.es.md
  guides/plugins/unofficial/vtex/common-errors.pt.md
  guides/plugins/unofficial/vtex/configure-payment-conditions.en.md
  guides/plugins/unofficial/vtex/configure-payment-conditions.es.md
  guides/plugins/unofficial/vtex/configure-payment-conditions.pt.md
  guides/plugins/unofficial/vtex/device-fingerprint.en.md
  guides/plugins/unofficial/vtex/device-fingerprint.es.md
  guides/plugins/unofficial/vtex/device-fingerprint.pt.md
  guides/plugins/unofficial/vtex/gateway-affiliations.en.md
  guides/plugins/unofficial/vtex/gateway-affiliations.es.md
  guides/plugins/unofficial/vtex/gateway-affiliations.pt.md
  guides/plugins/unofficial/vtex/introduction.en.md
  guides/plugins/unofficial/vtex/introduction.es.md
  guides/plugins/unofficial/vtex/introduction.pt.md
  guides/plugins/unofficial/vtex/logs.en.md
  guides/plugins/unofficial/vtex/logs.es.md
  guides/plugins/unofficial/vtex/logs.pt.md
  guides/plugins/unofficial/vtex/mp1-mp2-migration.en.md
  guides/plugins/unofficial/vtex/mp1-mp2-migration.es.md
  guides/plugins/unofficial/vtex/mp1-mp2-migration.pt.md
  guides/plugins/unofficial/vtex/payment-methods.en.md
  guides/plugins/unofficial/vtex/payment-methods.es.md
  guides/plugins/unofficial/vtex/payment-methods.pt.md
  guides/plugins/unofficial/vtex/prerequisites.en.md
  guides/plugins/unofficial/vtex/prerequisites.es.md
  guides/plugins/unofficial/vtex/prerequisites.pt.md
  images/vtex/affiliationV2-en.gif
  images/vtex/affiliationV2-es.gif
  images/vtex/affiliationV2-pt.gif
  images/vtex/devicefingerprint-en.gif
  images/vtex/devicefingerprint-es.gif
  images/vtex/devicefingerprint-pt.gif
  images/vtex/paymentconditions-cc-en.gif
  images/vtex/paymentconditions-cc-es.gif
  images/vtex/paymentconditions-cc-pt.gif
  images/vtex/paymentconditions-en.gif
  images/vtex/paymentconditions-es.gif
  images/vtex/paymentconditions-pt.gif
Labels: Ready to merge, menu modifications

#1375 T&C Update.
  guides/resources/legal/terms-and-conditions.en.md
  guides/resources/legal/terms-and-conditions.es.md
  guides/resources/legal/terms-and-conditions.pt.md
Labels: Don't merge, draft

#1431 Ajuste nas informações do Pix no CHO API
  guides/online-payments/checkout-api/other-payment-ways.en.md
  guides/online-payments/checkout-api/other-payment-ways.es.md
  guides/online-payments/checkout-api/other-payment-ways.pt.md
  guides/snippets/test-integration/pix-intro.en.md
  guides/snippets/test-integration/pix-intro.es.md
  guides/snippets/test-integration/pix-intro.pt.md
Labels: Ready to merge

#1441 arreglo de errores a pedido de legales
  guides/resources/legal/terms-and-conditions.en.md
  guides/resources/legal/terms-and-conditions.es.md
  guides/resources/legal/terms-and-conditions.pt.md
Labels: Ready to merge

#1442 Fix/vtex
  guides/plugins/unofficial/vtex/configure-payment-conditions.es.md
  guides/plugins/unofficial/vtex/introduction.en.md
  guides/plugins/unofficial/vtex/introduction.es.md
  guides/plugins/unofficial/vtex/introduction.pt.md
  images/vtex/affiliationV2-en.gif
  images/vtex/affiliationV2-es.gif
  images/vtex/affiliationV2-pt.gif
  images/vtex/devicefingerprint-en.gif
  images/vtex/devicefingerprint-es.gif
  images/vtex/devicefingerprint-pt.gif
  images/vtex/paymentconditions-cc-en.gif
  images/vtex/paymentconditions-cc-es.gif
  images/vtex/paymentconditions-cc-pt.gif
  images/vtex/paymentconditions-en.gif
  images/vtex/paymentconditions-es.gif
  images/vtex/paymentconditions-pt.gif
Labels: Ready to merge

#1437 Adicionar "devoluciones parciales" a MPE
  guides/manage-account/account/cancellations-and-refunds.en.md
  guides/manage-account/account/cancellations-and-refunds.es.md
  guides/manage-account/account/cancellations-and-refunds.pt.md
Labels: Ready to merge

#1460 feature/new refunds and cancellations apis
  reference/api/chargebacks.yaml
Labels: Ready to merge, changemenu

#1457 fix/Refunds and Cancellations doc update
  guides/manage-account/account/cancellations-and-refunds.en.md
  guides/manage-account/account/cancellations-and-refunds.es.md
  guides/manage-account/account/cancellations-and-refunds.pt.md
Labels: Ready to merge

#1407 Reescrevendo a documentação de Notifications
  guides/notifications/Introduction.en.md
  guides/notifications/Introduction.es.md
  guides/notifications/Introduction.pt.md
  guides/notifications/ipn-personal-payment.en.md
  guides/notifications/ipn-personal-payment.es.md
  guides/notifications/ipn-personal-payment.pt.md
  guides/notifications/ipn.en.md
  guides/notifications/ipn.es.md
  guides/notifications/ipn.pt.md
  guides/notifications/webhooks.en.md
  guides/notifications/webhooks.es.md
  guides/notifications/webhooks.pt.md
  guides/snippets/test-integration/notification-response.en.md
  guides/snippets/test-integration/notification-response.es.md
  guides/snippets/test-integration/notification-response.pt.md
  images/notifications/ipn__en.png
  images/notifications/ipn__es.png
  images/notifications/ipn__pt.png
  images/notifications/webhook_es.png
  images/notifications/webhooks_en.png
  images/notifications/webhooks_pt.png
Labels: changemenu

#1465 Actualizacion de T&C
  guides/resources/legal/terms-and-conditions.en.md
  guides/resources/legal/terms-and-conditions.es.md
  guides/resources/legal/terms-and-conditions.pt.md
Labels: Ready to merge

#1458 Nueva documentación oculta de Fields/Secure inputs
  guides/online-payments/checkout-api/receiving-payment-by-card-core-methods-v2.en.md
  guides/online-payments/checkout-api/receiving-payment-by-card-core-methods-v2.es.md
  guides/online-payments/checkout-api/receiving-payment-by-card-core-methods-v2.pt.md
  guides/online-payments/checkout-api/receiving-payment-by-card-core-methods.en.md
  guides/online-payments/checkout-api/receiving-payment-by-card-core-methods.es.md
  guides/online-payments/checkout-api/receiving-payment-by-card-core-methods.pt.md
  guides/online-payments/checkout-api/receiving-payment-by-card-v2.en.md
  guides/online-payments/checkout-api/receiving-payment-by-card-v2.es.md
  guides/online-payments/checkout-api/receiving-payment-by-card-v2.pt.md
  guides/security/pci-v2.en.md
  guides/security/pci-v2.es.md
  guides/security/pci-v2.pt.md
  guides/snippets/test-integration/api-payment-notifications.en.md
  guides/snippets/test-integration/api-payment-notifications.es.md
  guides/snippets/test-integration/api-payment-notifications.pt.md
  guides/snippets/test-integration/api-response-handling.en.md
  guides/snippets/test-integration/api-response-handling.es.md
  guides/snippets/test-integration/api-response-handling.pt.md
  guides/snippets/test-integration/receiving-payment-by-card.en.md
  guides/snippets/test-integration/receiving-payment-by-card.es.md
  guides/snippets/test-integration/receiving-payment-by-card.pt.md
  images/api/api-integration-flowchart-coremethods-v2-en.png
  images/api/api-integration-flowchart-coremethods-v2-es.png
  images/api/api-integration-flowchart-coremethods-v2-pt.png
  images/api/api-integration-introduction-v2-en.png
  images/api/api-integration-introduction-v2-es.png
  images/api/api-integration-introduction-v2-pt.png
Labels: Ready to merge, changemenu

#1417 feature/api-integraciones-documentation
  guides/in-person-payments/integration-api/create-payment-intent.en.md
  guides/in-person-payments/integration-api/create-payment-intent.es.md
  guides/in-person-payments/integration-api/create-payment-intent.pt.md
  guides/in-person-payments/integration-api/glossary.en.md
  guides/in-person-payments/integration-api/glossary.es.md
  guides/in-person-payments/integration-api/glossary.pt.md
  guides/in-person-payments/integration-api/integration.en.md
  guides/in-person-payments/integration-api/integration.es.md
  guides/in-person-payments/integration-api/integration.pt.md
  guides/in-person-payments/integration-api/introduction.en.md
  guides/in-person-payments/integration-api/introduction.es.md
  guides/in-person-payments/integration-api/introduction.pt.md
  guides/in-person-payments/integration-api/notifications.en.md
  guides/in-person-payments/integration-api/notifications.es.md
  guides/in-person-payments/integration-api/notifications.pt.md
  guides/in-person-payments/integration-api/point-simulator.en.md
  guides/in-person-payments/integration-api/point-simulator.es.md
  guides/in-person-payments/integration-api/point-simulator.pt.md
  guides/in-person-payments/mp-point/integration-api.es.md
Labels: Ready to merge, changemenu

#1428 new magento two documentation
  guides/plugins/magento-two/checkout-pro-configuration.en.md
  guides/plugins/magento-two/checkout-pro-configuration.es.md
  guides/plugins/magento-two/checkout-pro-configuration.pt.md
  guides/plugins/magento-two/instalation.en.md
  guides/plugins/magento-two/instalation.es.md
  guides/plugins/magento-two/instalation.pt.md
  guides/plugins/magento-two/introduction.en.md
  guides/plugins/magento-two/introduction.es.md
  guides/plugins/magento-two/introduction.pt.md
  guides/plugins/magento-two/notifications-configuration.en.md
  guides/plugins/magento-two/notifications-configuration.es.md
  guides/plugins/magento-two/notifications-configuration.pt.md
  guides/plugins/magento-two/payment-configuration.en.md
  guides/plugins/magento-two/payment-configuration.es.md
  guides/plugins/magento-two/payment-configuration.pt.md
  guides/plugins/magento-two/previous-requirements.en.md
  guides/plugins/magento-two/previous-requirements.es.md
  guides/plugins/magento-two/previous-requirements.pt.md
  images/magento2/magentotwo_classic_checkout.png
Labels: Ready to merge, changemenu

#1474 Migração de versão das Assinaturas
  guides/online-payments/subscriptions/migration-version.en.md
  guides/online-payments/subscriptions/migration-version.es.md
  guides/online-payments/subscriptions/migration-version.pt.md
  guides/online-payments/subscriptions/payment-retry.pt.md
Labels: Ready to merge
