Repository mercadopago/devsite-docs, pull requests merged in 2022-12, with the labels that each got.

#1907 fix/integration metrics process update
  guides/additional-content/metrics/integration-metrics.en.md
  guides/additional-content/metrics/integration-metrics.es.md
  guides/additional-content/metrics/integration-metrics.pt.md
Labels: Ready to merge

#1913 Feature/pgp-migration-key
  guides/additional-content/security/pci-migration-pgp.en.md
  guides/additional-content/security/pci-migration-pgp.es.md
  guides/additional-content/security/pci-migration-pgp.pt.md
Labels: Don't merge

#1926 fix/fraud allert link fix
  guides/additional-content/notifications/Introduction.en.md
  guides/additional-content/notifications/Introduction.es.md
  guides/additional-content/notifications/Introduction.pt.md
Labels: Ready to merge

#1902 fix/subscription doc curl and video tutorial insertion
  guides/subscriptions/introduction.en.md
  guides/subscriptions/introduction.es.md
  guides/subscriptions/introduction.pt.md
  guides/subscriptions/migration-version.en.md
  guides/subscriptions/migration-version.es.md
  guides/subscriptions/migration-version.pt.md
  guides/subscriptions/requirements.en.md
  guides/subscriptions/requirements.es.md
  guides/subscriptions/requirements.pt.md
  guides/subscriptions/subscription-management.en.md
  guides/subscriptions/subscription-management.es.md
  guides/subscriptions/subscription-management.pt.md
  guides/subscriptions/subscription-no-associated-plan.en.md
  guides/subscriptions/subscription-no-associated-plan.es.md
  guides/subscriptions/subscription-no-associated-plan.pt.md
  guides/subscriptions/subscriptions-associated-plan.en.md
  guides/subscriptions/subscriptions-associated-plan.es.md
  guides/subscriptions/subscriptions-associated-plan.pt.md
  guides/subscriptions/tutorial-videos.en.md
  guides/subscriptions/tutorial-videos.es.md
  guides/subscriptions/tutorial-videos.pt.md
  reference/api/subscriptions.yaml
Labels: Ready to merge

#1917 Feature/point-changes
  guides/integration-api/glossary.en.md
  guides/integration-api/glossary.es.md
  guides/integration-api/glossary.pt.md
  guides/integration-api/point-simulator.en.md
  guides/integration-api/point-simulator.es.md
  guides/integration-api/point-simulator.pt.md
  guides/mp-point/landing.es.md
  guides/mp-point/prerequisites.en.md
  guides/mp-point/prerequisites.es.md
  guides/mp-point/prerequisites.pt.md
  guides/mp-point/types-of-integration.en.md
  guides/mp-point/types-of-integration.es.md
  guides/mp-point/types-of-integration.pt.md
Labels: Ready to merge, menu modifications

#1867 [DEVCOMMS-1055] Feature/homologator
  guides/additional-content/dashboard/applications.en.md
  guides/additional-content/dashboard/applications.es.md
  guides/additional-content/dashboard/applications.pt.md
  guides/additional-content/homologator/homologator.en.md
  guides/additional-content/homologator/homologator.es.md
  guides/additional-content/homologator/homologator.pt.md
  images/homologator/integration-quality-es.png
  images/homologator/integration-quality-pt.png
Labels: Ready to merge

#1904 feature/salesforce-checkoutpro
  guides/salesforce/cho-pro-en.md
  guides/salesforce/cho-pro.es.md
  guides/salesforce/cho-pro.pt.md
  guides/salesforce/credit-debit-card.en.md
  guides/salesforce/credit-debit-card.es.md
  guides/salesforce/credit-debit-card.pt.md
  guides/salesforce/installation-verification.en.md
  guides/salesforce/installation-verification.es.md
  guides/salesforce/installation-verification.pt.md
  guides/salesforce/integration-test.en.md
  guides/salesforce/integration-test.es.md
  guides/salesforce/integration-test.pt.md
  guides/salesforce/landing.en.md
  guides/salesforce/landing.es.md
  guides/salesforce/landing.pt.md
  guides/salesforce/payment-configuration.en.md
  guides/salesforce/payment-configuration.es.md
  guides/salesforce/payment-configuration.pt.md
  guides/salesforce/payments-configuration.en.md
  guides/salesforce/payments-configuration.es.md
  guides/salesforce/payments-configuration.pt.md
  guides/salesforce/pix.en.md
  guides/salesforce/pix.es.md
  guides/salesforce/pix.pt.md
  guides/salesforce/plugin-integration.en.md
  guides/salesforce/plugin-integration.es.md
  guides/salesforce/plugin-integration.pt.md
  images/salesforce/chopro-br.png
  images/salesforce/payment_methods_v2.png
  images/shopify/config-ES.gif
Labels: Don't merge, In review, menu modifications

#1922 fix/payments api parameters improvement
  reference/api/payments.yaml
Labels: Ready to merge

#1930 Fix/chargebacks notifications
  guides/additional-content/chargebacks/how-to-prevent.en.md
  guides/additional-content/chargebacks/how-to-prevent.es.md
  guides/additional-content/chargebacks/how-to-prevent.pt.md
  guides/additional-content/notifications/Introduction.en.md
  guides/additional-content/notifications/Introduction.es.md
  guides/additional-content/notifications/Introduction.pt.md
Labels: Ready to merge

#1929 fix/payment link html code added
  guides/payment-link/share-website.en.md
  guides/payment-link/share-website.es.md
  guides/payment-link/share-website.pt.md
Labels: Ready to merge

#1927 feature/shopify images
  guides/shopify/configuration-checkout-api.en.md
  guides/shopify/configuration-checkout-api.es.md
  guides/shopify/configuration-checkout-api.pt.md
  guides/shopify/configuration-checkout-pro.en.md
  guides/shopify/configuration-checkout-pro.es.md
  guides/shopify/configuration-checkout-pro.pt.md
  guides/shopify/installation-checkout-api.en.md
  guides/shopify/installation-checkout-api.es.md
  guides/shopify/installation-checkout-api.pt.md
  guides/shopify/installation-checkout-pro.en.md
  guides/shopify/installation-checkout-pro.es.md
  guides/shopify/installation-checkout-pro.pt.md
  guides/shopify/integration-test-checkout-api.en.md
  guides/shopify/integration-test-checkout-api.es.md
  guides/shopify/integration-test-checkout-api.pt.md
  guides/shopify/integration-test-checkout-pro.en.md
  guides/shopify/integration-test-checkout-pro.es.md
  guides/shopify/integration-test-checkout-pro.pt.md
  guides/shopify/introduction-checkout-api.en.md
  guides/shopify/introduction-checkout-api.es.md
  guides/shopify/introduction-checkout-api.pt.md
  guides/shopify/introduction-checkout-pro.en.md
  guides/shopify/introduction-checkout-pro.es.md
  guides/shopify/introduction-checkout-pro.pt.md
  guides/shopify/requirements-checkout-api.en.md
  guides/shopify/requirements-checkout-api.es.md
  guides/shopify/requirements-checkout-api.pt.md
  guides/shopify/requirements-checkout-pro.en.md
  guides/shopify/requirements-checkout-pro.es.md
  guides/shopify/requirements-checkout-pro.pt.md
  images/shopify/cambiar-idioma-ES.png
  images/shopify/cambiar-idioma-PT.png
  images/shopify/company-name-es-v2.gif
  images/shopify/company-name-pt-v2.gif
  images/shopify/configurar-chotransparente-pt.gif
  images/shopify/configurar-empresa-ES.gif
  images/shopify/configurar-empresa-PT.gif
  images/shopify/install-chopro-ES.gif
  images/shopify/install-chopro-PT.gif
Labels: Don't merge
