Repository mercadopago/devsite-docs, pull requests merged in 2022-08, with the labels that each got.

#1797 fix/shopify-doc
  guides/shopify/chargebacks.es.md
Labels: menu modifications

#1800 fix/sdks version update
  guides/sdks-v2/official/server-side.en.md
  guides/sdks-v2/official/server-side.es.md
  guides/sdks-v2/official/server-side.pt.md
Labels: Ready to merge

#1799 fix/cho api card section title correction
  guides/checkout-api-v2/integration-via-cardform.en.md
  guides/checkout-api-v2/integration-via-cardform.es.md
  guides/checkout-api-v2/integration-via-cardform.pt.md
Labels: Ready to merge

#1802 fix/min and max amount fixes
  guides/subscriptions/requirements.en.md
  guides/subscriptions/requirements.es.md
  guides/subscriptions/requirements.pt.md
Labels: Ready to merge

#1794 feature/new wallet connect webhooks section
  guides/wallet-connect/create-agreement.en.md
  guides/wallet-connect/create-agreement.es.md
  guides/wallet-connect/create-agreement.pt.md
  guides/wallet-connect/notifications.en.md
  guides/wallet-connect/notifications.es.md
  guides/wallet-connect/notifications.pt.md
  images/wallet-connect/create-agreement.en.png
  images/wallet-connect/create-agreement.es.png
  images/wallet-connect/create-agreement.pt.png
  images/wallet-connect/new-create-agreement.en.png
  images/wallet-connect/new-create-agreement.es.png
  images/wallet-connect/new-create-agreement.pt.png
  reference/api/wallet_connect.yaml
  reference/base.yaml
Labels: Ready to merge

#1796 feature/tokenizer-migration-to-bricks
  guides/checkout-bricks/cardform-clientside.en.md
  guides/checkout-bricks/cardform-clientside.es.md
  guides/checkout-bricks/cardform-clientside.pt.md
  guides/checkout-bricks/howto-migrate.en.md
  guides/checkout-bricks/howto-migrate.es.md
  guides/checkout-bricks/howto-migrate.pt.md
  guides/checkout-bricks/web-tokenize-checkout-v1-clientside.en.md
  guides/checkout-bricks/web-tokenize-checkout-v1-clientside.es.md
  guides/checkout-bricks/web-tokenize-checkout-v1-clientside.pt.md
  guides/checkout-bricks/web-tokenize-checkout-v1-serverside.en.md
  guides/checkout-bricks/web-tokenize-checkout-v1-serverside.es.md
  guides/checkout-bricks/web-tokenize-checkout-v1-serverside.pt.md
  guides/checkout-bricks/web-tokenize-checkout-v2-clientside.en.md
  guides/checkout-bricks/web-tokenize-checkout-v2-clientside.es.md
  guides/checkout-bricks/web-tokenize-checkout-v2-clientside.pt.md
  guides/checkout-bricks/web-tokenize-checkout-v2-serverside.en.md
  guides/checkout-bricks/web-tokenize-checkout-v2-serverside.es.md
  guides/checkout-bricks/web-tokenize-checkout-v2-serverside.pt.md
  guides/web-tokenize-checkout/introduction.en.md
  guides/web-tokenize-checkout/introduction.es.md
  guides/web-tokenize-checkout/introduction.pt.md
  guides/web-tokenize-checkout/v1/web-tokenize-checkout-v1-clientside.en.md
  guides/web-tokenize-checkout/v1/web-tokenize-checkout-v1-clientside.es.md
  guides/web-tokenize-checkout/v1/web-tokenize-checkout-v1-clientside.pt.md
  guides/web-tokenize-checkout/v1/web-tokenize-checkout-v1-serverside.en.md
  guides/web-tokenize-checkout/v1/web-tokenize-checkout-v1-serverside.es.md
  guides/web-tokenize-checkout/v1/web-tokenize-checkout-v1-serverside.pt.md
  guides/web-tokenize-checkout/web-tokenize-checkout-v2-clientside.en.md
  guides/web-tokenize-checkout/web-tokenize-checkout-v2-clientside.es.md
  guides/web-tokenize-checkout/web-tokenize-checkout-v2-clientside.pt.md
  guides/web-tokenize-checkout/web-tokenize-checkout-v2-serverside.en.md
  guides/web-tokenize-checkout/web-tokenize-checkout-v2-serverside.es.md
  guides/web-tokenize-checkout/web-tokenize-checkout-v2-serverside.pt.md
Labels: Ready to merge

#1817 fix/point smart removal
  guides/integration-api/introduction.en.md
  guides/integration-api/introduction.es.md
  guides/integration-api/introduction.pt.md
Labels: Don't merge

#1819 fix/point api description fix
  reference/api/integrations_api.yaml
Labels: Ready to merge
