Repository mercadopago/devsite-docs, pull requests merged in 2022-05, with the labels that each got.

#1686 fix/shopify-minor-fixes
  guides/shopify/checkout-api-installation.en.md
  guides/shopify/checkout-api-installation.es.md
  guides/shopify/checkout-api-installation.pt.md
  guides/shopify/introduction.es.md
Labels: menu modifications

#1687 [DEVCOMMS-760] API de QR Modelo Dinámico
  reference/api/qr-dynamic.yaml
Labels: Ready to merge, changemenu

#1689 feature/api-payments-userdata
  reference/api/payments.yaml
Labels: Ready to merge
