Repository mercadopago/devsite-docs, pull requests merged in 2022-02, with the labels that each got.

#1537 Ajuste de pré requisito para integracao com QR
  guides/in-person-payments/qr-code/pre-requisites.en.md
  guides/in-person-payments/qr-code/pre-requisites.es.md
  guides/in-person-payments/qr-code/pre-requisites.pt.md
Labels: Don't merge

#1550 Fix/plugins and notifications
  guides/notifications/ipn/in-person-payments.en.md
  guides/notifications/ipn/in-person-payments.es.md
  guides/notifications/ipn/in-person-payments.pt.md
  guides/notifications/ipn/introduction.en.md
  guides/notifications/ipn/introduction.es.md
  guides/notifications/ipn/introduction.pt.md
  guides/notifications/ipn/online-payments.en.md
  guides/notifications/ipn/online-payments.es.md
  guides/notifications/ipn/online-payments.pt.md
  guides/notifications/webhooks/webhooks.en.md
  guides/notifications/webhooks/webhooks.es.md
  guides/notifications/webhooks/webhooks.pt.md
  guides/plugins/magento-two/introduction.en.md
  guides/plugins/magento-two/introduction.es.md
  guides/plugins/magento-two/introduction.pt.md
  guides/plugins/prestashop/introduction.en.md
  guides/plugins/prestashop/introduction.es.md
  guides/plugins/prestashop/introduction.pt.md
  guides/plugins/woocommerce/introduction.en.md
  guides/plugins/woocommerce/introduction.es.md
  guides/plugins/woocommerce/introduction.pt.md
Labels: changemenu

#1565 Release v4.9.1 - Prestashop
  guides/resources/changelog/current-year.en.md
  guides/resources/changelog/current-year.es.md
  guides/resources/changelog/current-year.pt.md
Labels: Ready to merge

#1563 fix/novascorrecoes
  guides/online-payments/subscriptions/integration.pt.md
Labels: Ready to merge

#1564 Release v4.9.0 - Prestashop
  guides/resources/changelog/current-year.en.md
  guides/resources/changelog/current-year.es.md
  guides/resources/changelog/current-year.pt.md
Labels: Ready to merge

#1566 Fix/dashboard
  guides/in-person-payments/qr-code/integration-test.en.md
  guides/in-person-payments/qr-code/integration-test.es.md
  guides/in-person-payments/qr-code/integration-test.pt.md
  guides/in-person-payments/qr-code/integrations-front.en.md
  guides/in-person-payments/qr-code/integrations-front.es.md
  guides/in-person-payments/qr-code/integrations-front.pt.md
  guides/in-person-payments/qr-code/qr-attended/integrations.en.md
  guides/in-person-payments/qr-code/qr-attended/integrations.es.md
  guides/in-person-payments/qr-code/qr-attended/integrations.pt.md
  guides/in-person-payments/qr-code/qr-dynamic/integrations-offline.en.md
  guides/in-person-payments/qr-code/qr-dynamic/integrations-offline.es.md
  guides/in-person-payments/qr-code/qr-dynamic/integrations-offline.pt.md
  guides/in-person-payments/qr-code/qr-dynamic/integrations.en.md
  guides/in-person-payments/qr-code/qr-dynamic/integrations.es.md
  guides/in-person-payments/qr-code/qr-dynamic/integrations.pt.md
  guides/manage-account/account/chargebacks.en.md
  guides/manage-account/account/chargebacks.es.md
  guides/manage-account/account/chargebacks.pt.md
  guides/manage-account/account/go-live-requirements.en.md
  guides/manage-account/account/go-live-requirements.es.md
  guides/manage-account/account/go-live-requirements.pt.md
  guides/notifications/Introduction.en.md
  guides/notifications/Introduction.es.md
  guides/notifications/Introduction.pt.md
  guides/notifications/ipn/online-payments.en.md
  guides/notifications/ipn/online-payments.es.md
  guides/notifications/ipn/online-payments.pt.md
  guides/online-payments/checkout-api/goto-production.en.md
  guides/online-payments/checkout-api/goto-production.es.md
  guides/online-payments/checkout-api/goto-production.pt.md
  guides/online-payments/checkout-api/receiving-payment-by-card-core-methods.en.md
  guides/online-payments/checkout-api/receiving-payment-by-card-core-methods.es.md
  guides/online-payments/checkout-api/receiving-payment-by-card-core-methods.pt.md
  guides/online-payments/checkout-api/receiving-payment-by-card.en.md
  guides/online-payments/checkout-api/receiving-payment-by-card.es.md
  guides/online-payments/checkout-api/receiving-payment-by-card.pt.md
  guides/online-payments/checkout-api/v1/goto-production.en.md
  guides/online-payments/checkout-api/v1/goto-production.es.md
  guides/online-payments/checkout-api/v1/goto-production.pt.md
  guides/online-payments/checkout-api/v1/receiving-payment-by-card.en.md
  guides/online-payments/checkout-api/v1/receiving-payment-by-card.es.md
  guides/online-payments/checkout-api/v1/receiving-payment-by-card.pt.md
  guides/online-payments/checkout-pro/advanced-integration.en.md
  guides/online-payments/checkout-pro/advanced-integration.es.md
  guides/online-payments/checkout-pro/advanced-integration.pt.md
  guides/online-payments/marketplace/checkout-api/goto-production.en.md
  guides/online-payments/marketplace/checkout-api/goto-production.es.md
  guides/online-payments/marketplace/checkout-api/goto-production.pt.md
  guides/plugins/woocommerce/integration.es.md
  guides/resources/changelog/migration-guides/ipn-ow-guide.es.md
  guides/resources/dashboard/applications.en.md
  guides/resources/dashboard/applications.es.md
  guides/resources/dashboard/applications.pt.md
  guides/security/oauth/creation.en.md
  guides/security/oauth/creation.es.md
  guides/security/oauth/creation.pt.md
Labels: Ready to merge

#1573 Fix/release347_marketplace
  guides/online-payments/marketplace/integrate-marketplace.en.md
  guides/online-payments/marketplace/integrate-marketplace.es.md
  guides/online-payments/marketplace/integrate-marketplace.pt.md
Labels: Ready to merge

#1578 Update pull_request_template.md
  .github/pull_request_template.md
Labels: Ready to merge

#1579 New versions woocommerce
  guides/resources/changelog/current-year.en.md
  guides/resources/changelog/current-year.es.md
  guides/resources/changelog/current-year.pt.md
Labels: Ready to merge

#1580 [DEVCOMMS-487] Imagens na doc do Dashboard
  guides/resources/dashboard/certification.es.md
  guides/resources/dashboard/certification.pt.md
  guides/security/oauth/videos.en.md
  images/dashboard/dashboard-certification_es.png
  images/dashboard/dashboard-certification_pt.png
Labels: Ready to merge

#1584 Fix/links - OAuth/Dashboard
  guides/online-payments/marketplace/integrate-marketplace.en.md
  guides/online-payments/marketplace/integrate-marketplace.es.md
  guides/online-payments/marketplace/integrate-marketplace.pt.md
  guides/resources/dashboard/header.en.md
  guides/resources/dashboard/header.es.md
  guides/resources/dashboard/header.pt.md
  guides/security/oauth/creation.en.md
  guides/security/oauth/creation.es.md
  guides/security/oauth/creation.pt.md
  guides/security/oauth/management.en.md
  guides/security/oauth/management.es.md
  guides/security/oauth/management.pt.md
Labels: Ready to merge

#1587 Correção ortográfica na doc do dashboard
  guides/resources/dashboard/applications.pt.md
Labels: Ready to merge

#1588 Updated vtex affiliation info with new field
  guides/plugins/unofficial/vtex/gateway-affiliations.es.md
Labels: Ready to merge

#1592 Update chargebacks.yaml
  reference/api/chargebacks.yaml
Labels: Ready to merge

#1577 [DEVCOMMS-675] Reescritura de la documentación de IPN
  guides/notifications/ipn/additional-tools.en.md
  guides/notifications/ipn/additional-tools.es.md
  guides/notifications/ipn/additional-tools.pt.md
  guides/notifications/ipn/apis-map.en.md
  guides/notifications/ipn/apis-map.es.md
  guides/notifications/ipn/apis-map.pt.md
  guides/notifications/ipn/in-person-payments.en.md
  guides/notifications/ipn/in-person-payments.es.md
  guides/notifications/ipn/in-person-payments.pt.md
  guides/notifications/ipn/inperson-configuration.en.md
  guides/notifications/ipn/inperson-configuration.es.md
  guides/notifications/ipn/inperson-configuration.pt.md
  guides/notifications/ipn/inperson-introduction.en.md
  guides/notifications/ipn/inperson-introduction.es.md
  guides/notifications/ipn/inperson-introduction.pt.md
  guides/notifications/ipn/inperson-notification-events.en.md
  guides/notifications/ipn/inperson-notification-events.es.md
  guides/notifications/ipn/inperson-notification-events.pt.md
  guides/notifications/ipn/inperson-order-query.en.md
  guides/notifications/ipn/inperson-order-query.es.md
  guides/notifications/ipn/inperson-order-query.pt.md
  guides/notifications/ipn/introduction.en.md
  guides/notifications/ipn/introduction.es.md
  guides/notifications/ipn/introduction.pt.md
  guides/notifications/ipn/online-payment-creation-config.en.md
  guides/notifications/ipn/online-payment-creation-config.es.md
  guides/notifications/ipn/online-payment-creation-config.pt.md
  guides/notifications/ipn/online-url-after-notification.en.md
  guides/notifications/ipn/online-url-after-notification.es.md
  guides/notifications/ipn/online-url-after-notification.pt.md
  guides/notifications/ipn/online-url-configuration.en.md
  guides/notifications/ipn/online-url-configuration.es.md
  guides/notifications/ipn/online-url-configuration.pt.md
  guides/notifications/ipn/troubleshooting.en.md
  guides/notifications/ipn/troubleshooting.es.md
  guides/notifications/ipn/troubleshooting.pt.md
Labels: Ready to merge, changemenu

#1596 [DEVCOMMS-488] Test user API update
  guides/snippets/test-integration/create-test-users.en.md
  guides/snippets/test-integration/create-test-users.es.md
  guides/snippets/test-integration/create-test-users.pt.md
  reference/api/test-user.yaml
Labels: Ready to merge, changemenu
