Repository mercadopago/devsite-docs, pull requests merged in 2022-09, with the labels that each got.

#1828 [DEVCOMMS-1199] Feature/payment-methods
  guides/additional-content/getting-started/getting-started.en.md
  guides/additional-content/getting-started/getting-started.es.md
  guides/additional-content/getting-started/getting-started.pt.md
  guides/additional-content/payment-localization/consult-payment-methods.en.md
  guides/additional-content/payment-localization/consult-payment-methods.es.md
  guides/additional-content/payment-localization/consult-payment-methods.pt.md
  guides/additional-content/sales-processing/payment-methods.en.md
  guides/additional-content/sales-processing/payment-methods.es.md
  guides/additional-content/sales-processing/payment-methods.pt.md
  guides/checkout-api-v2/landing.en.md
  guides/checkout-api-v2/landing.es.md
  guides/checkout-api-v2/landing.pt.md
  guides/checkout-pro/landing.en.md
  guides/checkout-pro/landing.es.md
  guides/checkout-pro/landing.pt.md
  guides/magento-two/landing.en.md
  guides/magento-two/landing.es.md
  guides/magento-two/landing.pt.md
  guides/mp-delivery/landing.en.md
  guides/mp-delivery/landing.es.md
  guides/mp-delivery/landing.pt.md
  guides/mp-point/landing.en.md
  guides/mp-point/landing.es.md
  guides/mp-point/landing.pt.md
  guides/prestashop/landing.en.md
  guides/prestashop/landing.es.md
  guides/prestashop/landing.pt.md
  guides/qr-code/landing.en.md
  guides/qr-code/landing.es.md
  guides/qr-code/landing.pt.md
  guides/shopify/landing.en.md
  guides/shopify/landing.es.md
  guides/shopify/landing.pt.md
  guides/subscriptions/landing.en.md
  guides/subscriptions/landing.es.md
  guides/subscriptions/landing.pt.md
  guides/wallet-connect/landing.en.md
  guides/wallet-connect/landing.es.md
  guides/wallet-connect/landing.pt.md
Labels: Don't merge

#1823 fix/added chargebacks link on notifications doc
  guides/additional-content/notifications/Introduction.en.md
  guides/additional-content/notifications/Introduction.es.md
  guides/additional-content/notifications/Introduction.pt.md
  guides/additional-content/sales-processing/chargebacks.en.md
  guides/additional-content/sales-processing/chargebacks.es.md
  guides/additional-content/sales-processing/chargebacks.pt.md
Labels: Ready to merge

#1767 [DEVCOMMS-1050] Feature/Yampi - new doc
  guides/snippets/test-integration/create-test-users.en copy.md
  guides/snippets/test-integration/create-test-users.es copy.md
  guides/snippets/test-integration/create-test-users.pt copy.md
  guides/woocommerce/landing.en.md
  guides/woocommerce/landing.es.md
  guides/woocommerce/landing.pt.md
  guides/yampi/integration.en.md
  guides/yampi/integration.es.md
  guides/yampi/integration.pt.md
  guides/yampi/landing.en.md
  guides/yampi/landing.es.md
  guides/yampi/landing.pt.md
  guides/yampi/payment-configuration-cho-api.en.md
  guides/yampi/payment-configuration-cho-api.es.md
  guides/yampi/payment-configuration-cho-api.pt.md
  guides/yampi/prerequisites.en.md
  guides/yampi/prerequisites.es.md
  guides/yampi/prerequisites.pt.md
  images/yampi/landing-en.png
  images/yampi/landing.png
Labels: Ready to merge, changemenu

#1830 fix/tiendanube
  guides/nuvemshop/configuration.en.md
  guides/nuvemshop/configuration.es.md
  guides/nuvemshop/configuration.pt.md
  guides/nuvemshop/introduction.en.md
  guides/nuvemshop/introduction.es.md
  guides/nuvemshop/introduction.pt.md
  guides/nuvemshop/payment-methods.en.md
  guides/nuvemshop/payment-methods.es.md
  guides/nuvemshop/payment-methods.pt.md
Labels: menu modifications

#1835 Se agregan documentación para nuevos campos business_unit y sub_unit en los reportes Settlement y Release
  guides/additional-content/reports/account-money/glossary.en.md
  guides/additional-content/reports/account-money/glossary.es.md
  guides/additional-content/reports/account-money/glossary.pt.md
  guides/additional-content/reports/released-money/glossary.en.md
  guides/additional-content/reports/released-money/glossary.es.md
  guides/additional-content/reports/released-money/glossary.pt.md
Labels: Ready to merge

#1839 fix/payment methods landing components
  guides/checkout-api-v2/landing.en.md
  guides/checkout-api-v2/landing.es.md
  guides/checkout-api-v2/landing.pt.md
  guides/checkout-pro/landing.en.md
  guides/checkout-pro/landing.es.md
  guides/checkout-pro/landing.pt.md
  guides/magento-two/landing.en.md
  guides/magento-two/landing.es.md
  guides/magento-two/landing.pt.md
  guides/mp-delivery/landing.en.md
  guides/mp-delivery/landing.es.md
  guides/mp-delivery/landing.pt.md
  guides/prestashop/landing.en.md
  guides/prestashop/landing.es.md
  guides/prestashop/landing.pt.md
  guides/qr-code/landing.en.md
  guides/qr-code/landing.es.md
  guides/qr-code/landing.pt.md
  guides/shopify/landing.en.md
  guides/shopify/landing.es.md
  guides/shopify/landing.pt.md
  guides/subscriptions/landing.en.md
  guides/subscriptions/landing.es.md
  guides/subscriptions/landing.pt.md
  guides/woocommerce/landing.en.md
  guides/woocommerce/landing.es.md
  guides/woocommerce/landing.pt.md
  guides/yampi/landing.en.md
  guides/yampi/landing.es.md
  guides/yampi/landing.pt.md
Labels: Ready to merge

#1840 fix/added application as a prerequisite in every doc
  guides/checkout-api-v2/prerequisites.en.md
  guides/checkout-api-v2/prerequisites.es.md
  guides/checkout-api-v2/prerequisites.pt.md
  guides/checkout-bricks/card-payment-brick/prerequisites.en.md
  guides/checkout-bricks/card-payment-brick/prerequisites.es.md
  guides/checkout-bricks/card-payment-brick/prerequisites.pt.md
  guides/checkout-bricks/payment-brick/prerequisites.en.md
  guides/checkout-bricks/payment-brick/prerequisites.es.md
  guides/checkout-bricks/payment-brick/prerequisites.pt.md
  guides/magento-two/prerequisites.en.md
  guides/magento-two/prerequisites.es.md
  guides/magento-two/prerequisites.pt.md
  guides/prestashop/prerequisites.en.md
  guides/prestashop/prerequisites.es.md
  guides/prestashop/prerequisites.pt.md
  guides/shopify/requirements-checkout-api.en.md
  guides/shopify/requirements-checkout-api.es.md
  guides/shopify/requirements-checkout-api.pt.md
  guides/shopify/requirements-checkout-pro.en.md
  guides/shopify/requirements-checkout-pro.es.md
  guides/shopify/requirements-checkout-pro.pt.md
  guides/subscriptions/requirements.en.md
  guides/subscriptions/requirements.es.md
  guides/subscriptions/requirements.pt.md
  guides/woocommerce/requirements.en.md
  guides/woocommerce/requirements.es.md
  guides/woocommerce/requirements.pt.md
Labels: Ready to merge

#1834 Changes for mexico and argentina added
  guides/additional-content/reports/available-money/generate.en.md
  guides/additional-content/reports/available-money/generate.es.md
  guides/additional-content/reports/available-money/generate.pt.md
  guides/additional-content/reports/available-money/glossary.en.md
  guides/additional-content/reports/available-money/glossary.es.md
  guides/additional-content/reports/available-money/glossary.pt.md
  guides/additional-content/reports/available-money/how-to-use.en.md
  guides/additional-content/reports/available-money/how-to-use.es.md
  guides/additional-content/reports/available-money/how-to-use.pt.md
  guides/additional-content/reports/available-money/introduction.en.md
  guides/additional-content/reports/available-money/introduction.es.md
  guides/additional-content/reports/available-money/introduction.pt.md
  guides/additional-content/reports/available-money/panel.en.md
  guides/additional-content/reports/available-money/panel.pt.md
  guides/additional-content/reports/released-money/introduction.en.md
  guides/additional-content/reports/released-money/introduction.es.md
Labels: Ready to merge

#1841 fix/updated point integration api section
  guides/integration-api/integration.en.md
  guides/integration-api/integration.es.md
  guides/integration-api/integration.pt.md
  guides/mp-point/how-to-integrate.en.md
  guides/mp-point/how-to-integrate.es.md
  guides/mp-point/how-to-integrate.pt.md
  guides/mp-point/landing.en.md
  guides/mp-point/landing.es.md
  guides/mp-point/landing.pt.md
  guides/mp-point/without-integration.en.md
  guides/mp-point/without-integration.es.md
  guides/mp-point/without-integration.pt.md
Labels: Ready to merge

#1842 fix/VTEX doc link correction
  guides/vtex/logs.en.md
  guides/vtex/logs.es.md
  guides/vtex/logs.pt.md
Labels: Ready to merge

#1851 fix/point smart mla removal
  guides/integration-api/introduction.en.md
  guides/integration-api/introduction.es.md
Labels: Ready to merge

#1852 fix/fraud alerts event correction
  guides/additional-content/notifications/ipn/online-url-configuration.en.md
  guides/additional-content/notifications/ipn/online-url-configuration.es.md
  guides/additional-content/notifications/ipn/online-url-configuration.pt.md
Labels: Ready to merge

#1849 fix/subscriptions doc and api fixes
  guides/additional-content/testing/test-purchase.en.md
  guides/additional-content/testing/test-purchase.es.md
  guides/additional-content/testing/test-purchase.pt.md
  reference/api/subscriptions.yaml
Labels: Ready to merge

#1846 feature/new point apis added
  reference/api/integrations_api.yaml
Labels: Ready to merge
