Repository mercadopago/devsite-docs, pull requests merged in 2022-03, with the labels that each got.

#1439 feature/new shopify hpsdk documentation
  guides/plugins/official/shopify.en.md
  guides/plugins/official/shopify.es.md
  guides/plugins/official/shopify.pt.md
  guides/snippets/test-integration/shopify-cpf-config.en.md
  guides/snippets/test-integration/shopify-cpf-config.es.md
  guides/snippets/test-integration/shopify-cpf-config.pt.md
  guides/snippets/test-integration/shopify-test-purchase.en.md
  guides/snippets/test-integration/shopify-test-purchase.es.md
  guides/snippets/test-integration/shopify-test-purchase.pt.md
Labels: Ready to merge

#1591 [DEVCOMMS-685] Incrementar Endpoint CHO PRO
  reference/api/payment_methods.yaml
  reference/api/preferences.yaml
Labels: Ready to merge

#1599 [DEVCOMMS-675] Incremento endpoints de IPN
  reference/api/chargebacks.yaml
  reference/api/merchant_orders.yaml
  reference/api/payments.yaml
Labels: Ready to merge

#1603 Update introduction.pt.md
  guides/manage-account/reports/account-money/introduction.pt.md
Labels: Ready to merge

#1604 Update how-to-use.pt.md
  guides/manage-account/reports/account-money/how-to-use.pt.md
Labels: Ready to merge

#1605 Update glossary.pt.md
  guides/manage-account/reports/account-money/glossary.pt.md
Labels: Ready to merge

#1601 [DEVCOMMS-685] Arreglo de errores de traducción
  reference/api/preferences.yaml
Labels: Ready to merge

#1617 [DEVCOMMS-827] Update Create Customer API
  reference/api/customers.yaml
Labels: Ready to merge

#1621 Modificación de titulos API reference
  reference/api/preferences.yaml
Labels: Ready to merge, changemenu

#1586 [DEVCOMMS-476] CashOut para QR
  guides/in-person-payments/qr-code/apiref-map.en.md
  guides/in-person-payments/qr-code/apiref-map.es.md
  guides/in-person-payments/qr-code/apiref-map.pt.md
  guides/in-person-payments/qr-code/cashout.en.md
  guides/in-person-payments/qr-code/cashout.es.md
  guides/in-person-payments/qr-code/cashout.pt.md
  reference/api/cashout-qr.yaml
  reference/base.yaml
Labels: Ready to merge, changemenu

#1612 [DEVCOMMS-685] Modificación de descripciones de API reference
  reference/api/chargebacks.yaml
  reference/api/merchant_orders.yaml
  reference/api/payments.yaml
  reference/api/preferences.yaml
Labels: Don't merge, draft

#1634 Release v4.10.0 - Prestashop and v3.15.0 - Magento 2
  guides/resources/changelog/current-year.en.md
  guides/resources/changelog/current-year.es.md
  guides/resources/changelog/current-year.pt.md
Labels: Ready to merge

#1633 Feature/PPWP-802 discontinuation prestashop 1.6
  guides/plugins/prestashop/introduction.en.md
  guides/plugins/prestashop/introduction.es.md
  guides/plugins/prestashop/introduction.pt.md
  guides/plugins/prestashop/previous-requirements.en.md
  guides/plugins/prestashop/previous-requirements.es.md
  guides/plugins/prestashop/previous-requirements.pt.md
Labels: Ready to merge

#1631 Update point-simulator.en.md
  guides/in-person-payments/integration-api/point-simulator.en.md
Labels: Ready to merge

#1629 Update point-simulator.pt.md
  guides/in-person-payments/integration-api/point-simulator.pt.md
Labels: Ready to merge

#1632 [DEVCOMMS-465] Secure Fields snippets
  guides/online-payments/checkout-api/receiving-payment-by-card-core-methods-v2.en.md
  guides/online-payments/checkout-api/receiving-payment-by-card-core-methods-v2.es.md
  guides/online-payments/checkout-api/receiving-payment-by-card-core-methods-v2.pt.md
  guides/online-payments/checkout-api/receiving-payment-by-card-v2.en.md
  guides/online-payments/checkout-api/receiving-payment-by-card-v2.es.md
  guides/online-payments/checkout-api/receiving-payment-by-card-v2.pt.md
  guides/snippets/test-integration/secure-fields-card.en.md
  guides/snippets/test-integration/secure-fields-card.es.md
  guides/snippets/test-integration/secure-fields-card.pt.md
  guides/snippets/test-integration/secure-fields-core.en.md
  guides/snippets/test-integration/secure-fields-core.es.md
  guides/snippets/test-integration/secure-fields-core.pt.md
Labels: Don't merge, draft

#1643 [DEVCOMMS-468] Modificación en referencia de API de preferencias
  reference/api/preferences.yaml
Labels: Don't merge

#1644 Adicionar campo "tarjeta de crédito" en Glosario del reporte de liberaciones
  guides/manage-account/reports/released-money/glossary.en.md
  guides/manage-account/reports/released-money/glossary.es.md
  guides/manage-account/reports/released-money/glossary.pt.md
Labels: Ready to merge

#1645 Agregar información de notificación por webhook para la generación de reportes de todas las transacciones y liberaciones
  guides/manage-account/reports/account-money/generate.en.md
  guides/manage-account/reports/account-money/generate.es.md
  guides/manage-account/reports/account-money/generate.pt.md
  guides/manage-account/reports/released-money/generate.en.md
  guides/manage-account/reports/released-money/generate.es.md
  guides/manage-account/reports/released-money/generate.pt.md
Labels: Ready to merge

#1620 Rename fields cvv
  guides/snippets/test-integration/receiving-payment-by-card.en.md
  guides/snippets/test-integration/receiving-payment-by-card.es.md
  guides/snippets/test-integration/receiving-payment-by-card.pt.md
  guides/snippets/test-integration/secure-fields-card.en.md
  guides/snippets/test-integration/secure-fields-card.es.md
  guides/snippets/test-integration/secure-fields-card.pt.md
  guides/snippets/test-integration/secure-fields-core.en.md
  guides/snippets/test-integration/secure-fields-core.es.md
  guides/snippets/test-integration/secure-fields-core.pt.md
Labels: Don't merge
