Repository mercadopago/devsite-docs, pull requests merged in 2023-08, with the labels that each got.

#2113 fix/snippet-testusers-credentials
  guides/snippets/test-integration/create-test-users.en.md
  guides/snippets/test-integration/create-test-users.es.md
  guides/snippets/test-integration/create-test-users.pt.md
Labels: Ready to merge

#2128 Guia de Escrita - tradução pro português
  guides/additional-content/style-guide/abbreviations.pt.md
  guides/additional-content/style-guide/bold-and-italics.pt.md
  guides/additional-content/style-guide/bullets.pt.md
  guides/additional-content/style-guide/clickstream.pt.md
  guides/additional-content/style-guide/documentation-scannability.es.md
  guides/additional-content/style-guide/documentation-scannability.pt.md
  guides/additional-content/style-guide/enumerations.pt.md
  guides/additional-content/style-guide/guide-stucture.pt.md
  guides/additional-content/style-guide/highlights.pt.md
  guides/additional-content/style-guide/images.pt.md
  guides/additional-content/style-guide/landing.pt.md
  guides/additional-content/style-guide/links.pt.md
  guides/additional-content/style-guide/menu-style.pt.md
  guides/additional-content/style-guide/notes.pt.md
  guides/additional-content/style-guide/paragraphs-sentences-titles.pt.md
  guides/additional-content/style-guide/passive-active-voice.pt.md
  guides/additional-content/style-guide/pronouns.pt.md
  guides/additional-content/style-guide/punctuation.pt.md
  guides/additional-content/style-guide/tables.pt.md
  guides/additional-content/style-guide/tenses-verbal-modes.pt.md
  guides/additional-content/style-guide/titles.pt.md
  guides/additional-content/style-guide/translations-language-specifics.pt.md
  guides/additional-content/style-guide/uppercaps.pt.md
  guides/additional-content/style-guide/uses-of-gerund.pt.md
  guides/additional-content/style-guide/voice-and-tone.pt.md
  images/style-guide/menu-example-pt.png
  images/style-guide/nota-esclarecimento-pt.png
  images/style-guide/nota-precaucao.png
  images/style-guide/nota-simples-pt.png
  images/style-guide/table-example-pt.png
Labels: menu modifications

#2130 feature/new wallet connect endpoint
  reference/api/wallet_connect.yaml
Labels: Ready to merge

#2129 Modificaciones para Webhook
  guides/additional-content/chargebacks/how-to-prevent.en.md
  guides/additional-content/chargebacks/how-to-prevent.es.md
  guides/additional-content/chargebacks/how-to-prevent.pt.md
  guides/additional-content/your-integrations/webhooks.en.md
  guides/additional-content/your-integrations/webhooks.es.md
  guides/additional-content/your-integrations/webhooks.pt.md
Labels: Don't merge

#2138 fix/updated sdk server side landing text
  guides/sdks-v2/official/landing.en.md
  guides/sdks-v2/official/landing.es.md
  guides/sdks-v2/official/landing.pt.md
  guides/sdks-v2/official/server-side.en.md
  guides/sdks-v2/official/server-side.es.md
  guides/sdks-v2/official/server-side.pt.md
Labels: Ready to merge

#2140 feature/cho-pro-mobile-integration
  guides/checkout-pro/integrate-chopro-mobile.en.md
  guides/checkout-pro/integrate-chopro-mobile.es.md
  guides/checkout-pro/integrate-chopro-mobile.pt.md
  guides/checkout-pro/integrate-chopro-web.en.md
  guides/checkout-pro/integrate-chopro-web.es.md
  guides/checkout-pro/integrate-chopro-web.pt.md
  guides/checkout-pro/integrate-preferences.en.md
  guides/checkout-pro/integrate-preferences.es.md
  guides/checkout-pro/integrate-preferences.pt.md
  guides/checkout-pro/integration-android-java-kotlin.en.md
  guides/checkout-pro/integration-android-java-kotlin.es.md
  guides/checkout-pro/integration-android-java-kotlin.pt.md
  guides/checkout-pro/integration-android-reactnative-cli.en.md
  guides/checkout-pro/integration-android-reactnative-cli.es.md
  guides/checkout-pro/integration-android-reactnative-cli.pt.md
  guides/checkout-pro/integration-android-reactnative-expo-go.en.md
  guides/checkout-pro/integration-android-reactnative-expo-go.es.md
  guides/checkout-pro/integration-android-reactnative-expo-go.pt.md
  guides/checkout-pro/integration-ios-reactnative-cli.en.md
  guides/checkout-pro/integration-ios-reactnative-cli.es.md
  guides/checkout-pro/integration-ios-reactnative-cli.pt.md
  guides/checkout-pro/integration-ios-reactnative-expo-go.en.md
  guides/checkout-pro/integration-ios-reactnative-expo-go.es.md
  guides/checkout-pro/integration-ios-reactnative-expo-go.pt.md
  guides/checkout-pro/integration-ios-swift.en.md
  guides/checkout-pro/integration-ios-swift.es.md
  guides/checkout-pro/integration-ios-swift.pt.md
Labels: In review, changemenu
