Repository mercadopago/devsite-docs, pull requests merged in 2023-12, with the labels that each got.

#2196 feature/wallet connect coupon endpoints
  guides/wallet-connect/coupon-validation-responses.en.md
  guides/wallet-connect/coupon-validation-responses.es.md
  guides/wallet-connect/coupon-validation-responses.pt.md
  guides/wallet-connect/create-agreement.en.md
  guides/wallet-connect/create-agreement.es.md
  guides/wallet-connect/create-agreement.pt.md
  guides/wallet-connect/create-discount-promise-with-coupon.en.md
  guides/wallet-connect/create-discount-promise-with-coupon.es.md
  guides/wallet-connect/create-discount-promise-with-coupon.pt.md
  guides/wallet-connect/create-discount-promise-without-coupon.en.md
  guides/wallet-connect/create-discount-promise-without-coupon.es.md
  guides/wallet-connect/create-discount-promise-without-coupon.pt.md
  guides/wallet-connect/create-payer-token.en.md
  guides/wallet-connect/create-payer-token.es.md
  guides/wallet-connect/create-payer-token.pt.md
  guides/wallet-connect/discount-promise-no-coupon-responses.en.md
  guides/wallet-connect/discount-promise-no-coupon-responses.es.md
  guides/wallet-connect/discount-promise-no-coupon-responses.pt.md
  guides/wallet-connect/discounts-intro.en.md
  guides/wallet-connect/discounts-intro.es.md
  guides/wallet-connect/discounts-intro.pt.md
  guides/wallet-connect/get-approval.en.md
  guides/wallet-connect/get-approval.es.md
  guides/wallet-connect/get-approval.pt.md
  guides/wallet-connect/notifications.en.md
  guides/wallet-connect/notifications.es.md
  guides/wallet-connect/notifications.pt.md
  guides/wallet-connect/process-payments-with-discounts.en.md
  guides/wallet-connect/process-payments-with-discounts.es.md
  guides/wallet-connect/process-payments-with-discounts.pt.md
  images/wallet-connect/create-payer-token-v2-en.png
  images/wallet-connect/create-payer-token-v2-es.png
  images/wallet-connect/create-payer-token-v2-pt.png
  reference/api-json/payments.json
  reference/api-json/wallet_connect.json
  reference/api/wallet_connect.yaml
Labels: Ready to merge

#2212 fix/checkout api fix the basics dinamic adjustments
  guides/additional-content/sales-processing/cancellations-and-refunds.pt.md
  guides/checkout-api-v2/capture-authorized-payment.en.md
  guides/checkout-api-v2/capture-authorized-payment.es.md
  guides/checkout-api-v2/capture-authorized-payment.pt.md
  guides/checkout-api-v2/installments-without-card.en.md
  guides/checkout-api-v2/installments-without-card.es.md
  guides/checkout-api-v2/installments-without-card.pt.md
  guides/checkout-api-v2/integration-via-cardform.en.md
  guides/checkout-api-v2/integration-via-cardform.es.md
  guides/checkout-api-v2/integration-via-cardform.pt.md
  guides/checkout-api-v2/other-payment-methods.es.md
  guides/checkout-api-v2/other-payment-methods.pt.md
  guides/checkout-api-v2/prerequisites.es.md
  guides/checkout-api-v2/types-of-integration.en.md
  guides/checkout-api-v2/types-of-integration.es.md
  guides/checkout-api-v2/types-of-integration.pt.md
Labels: Ready to merge

#2204 fix/payments api parameters improvements
  guides/checkout-pro/integration-android-flutter.en.md
  guides/checkout-pro/integration-android-flutter.es.md
  guides/checkout-pro/integration-android-flutter.pt.md
  guides/checkout-pro/integration-android-java-kotlin.en.md
  guides/checkout-pro/integration-android-java-kotlin.es.md
  guides/checkout-pro/integration-android-java-kotlin.pt.md
  guides/checkout-pro/integration-android-reactnative-cli.en.md
  guides/checkout-pro/integration-android-reactnative-cli.es.md
  guides/checkout-pro/integration-android-reactnative-cli.pt.md
  guides/checkout-pro/integration-android-reactnative-expo-go.en.md
  guides/checkout-pro/integration-android-reactnative-expo-go.es.md
  guides/checkout-pro/integration-android-reactnative-expo-go.pt.md
  reference/api-json/base.json
  reference/api-json/cards.json
  reference/api-json/customers.json
  reference/api-json/payments.json
  reference/api-json/preferences.json
  reference/api-json/test_user.json
  reference/api/base.yaml
  reference/api/payments.yaml
Labels: Ready to merge

#2232 Fix/minor fixes in docs
  guides/checkout-pro/integration-android-flutter.en.md
  guides/checkout-pro/integration-android-flutter.es.md
  guides/checkout-pro/integration-android-flutter.pt.md
  guides/checkout-pro/integration-android-java-kotlin.en.md
  guides/checkout-pro/integration-android-java-kotlin.pt.md
  guides/checkout-pro/integration-android-reactnative-cli.en.md
  guides/checkout-pro/integration-android-reactnative-cli.es.md
  guides/checkout-pro/integration-android-reactnative-cli.pt.md
  guides/checkout-pro/integration-android-reactnative-expo-go.en.md
  guides/checkout-pro/integration-android-reactnative-expo-go.es.md
  guides/checkout-pro/integration-android-reactnative-expo-go.pt.md
  guides/mp-delivery/cancel-order.es.md
Labels: Ready to merge

#2234 Se agrega descripción en sección checkout-pro/additional-content/reports/released-money/report-use
  guides/additional-content/reports/released-money/glossary.es.md
Labels: Don't merge

#2236 fix/wallet connect curls update
  guides/wallet-connect/create-payer-token.en.md
  guides/wallet-connect/create-payer-token.es.md
  guides/wallet-connect/create-payer-token.pt.md
  reference/api-json/wallet_connect.json
Labels: Ready to merge

#2215 feature/psea-choapi
  guides/checkout-api-v2/errors-pse.en.md
  guides/checkout-api-v2/errors-pse.es.md
  guides/checkout-api-v2/errors-pse.pt.md
  guides/checkout-api-v2/how-to-migrate-pse.en.md
  guides/checkout-api-v2/how-to-migrate-pse.es.md
  guides/checkout-api-v2/how-to-migrate-pse.pt.md
  guides/checkout-api-v2/integrate-pse-avanza.en.md
  guides/checkout-api-v2/integrate-pse-avanza.es.md
  guides/checkout-api-v2/integrate-pse-avanza.pt.md
  guides/checkout-api-v2/legacy-integrate-pse.en.md
  guides/checkout-api-v2/legacy-integrate-pse.es.md
  guides/checkout-api-v2/legacy-integrate-pse.pt.md
  images/api/pse-callback-approved.png
  images/api/pse-callback-pending.png
  images/api/pse-callback-rejected.png
Labels: menu modifications

#2244 feature/deprecado-modal
  guides/adobe-commerce/checkout-pro.en.md
  guides/adobe-commerce/checkout-pro.es.md
  guides/adobe-commerce/checkout-pro.pt.md
  guides/adobe-commerce/upgrade-to-the-new-plugin.en.md
  guides/adobe-commerce/upgrade-to-the-new-plugin.es.md
  guides/adobe-commerce/upgrade-to-the-new-plugin.pt.md
  guides/checkout-bricks/payment-brick/preferences.en.md
  guides/checkout-bricks/payment-brick/preferences.es.md
  guides/checkout-bricks/payment-brick/preferences.pt.md
  guides/checkout-bricks/wallet-brick/opening-mode.en.md
  guides/checkout-bricks/wallet-brick/opening-mode.es.md
  guides/checkout-bricks/wallet-brick/opening-mode.pt.md
  guides/checkout-bricks/wallet-brick/preferences.en.md
  guides/checkout-bricks/wallet-brick/preferences.es.md
  guides/checkout-bricks/wallet-brick/preferences.pt.md
  guides/checkout-pro/add-checkout.en.md
  guides/checkout-pro/auxiliary-callbacks.en.md
  guides/checkout-pro/auxiliary-callbacks.es.md
  guides/checkout-pro/auxiliary-callbacks.pt.md
  guides/checkout-pro/integrate-checkout.en.md
  guides/checkout-pro/integrate-checkout.es.md
  guides/checkout-pro/integrate-checkout.pt.md
  guides/checkout-pro/integrate-chopro-web.en.md
  guides/checkout-pro/integrate-chopro-web.es.md
  guides/checkout-pro/integrate-chopro-web.pt.md
  guides/checkout-pro/legacy/color-style.en.md
  guides/checkout-pro/legacy/color-style.es.md
  guides/checkout-pro/legacy/color-style.pt.md
  guides/checkout-pro/opening-schema.en.md
  guides/checkout-pro/opening-schema.es.md
  guides/checkout-pro/opening-schema.pt.md
  guides/checkout-pro/redirection.en.md
  guides/checkout-pro/redirection.es.md
  guides/checkout-pro/redirection.pt.md
  guides/prestashop/payment-configuration-cho-pro.en.md
  guides/prestashop/payment-configuration-cho-pro.es.md
  guides/prestashop/payment-configuration-cho-pro.pt.md
Labels: Don't merge

#2222 feature/new-claims-endpoint
  guides/additional-content/your-integrations/webhooks.en.md
  guides/additional-content/your-integrations/webhooks.es.md
  guides/additional-content/your-integrations/webhooks.pt.md
  images/claims/api-claim-en.gif
  images/claims/api-claim-es.gif
  images/claims/api-claim-pt.gif
  images/claims/api-claims-en.gif
  images/claims/api-claims-en.png
  images/claims/api-claims-es.gif
  images/claims/api-claims-es.png
  images/claims/api-claims-pt.gif
  images/claims/api-claims-pt.png
  reference/api-json/claims.json
Labels: Ready to merge

#2249 Revisão das documentações funcionais de relatórios
  guides/additional-content/reports/general-considerations/reconciliation-reports.en.md
  guides/additional-content/reports/general-considerations/reconciliation-reports.es.md
  guides/additional-content/reports/general-considerations/reconciliation-reports.pt.md
  guides/additional-content/reports/released-money/api.en.md
  guides/additional-content/reports/released-money/api.es.md
  guides/additional-content/reports/released-money/api.pt.md
  guides/additional-content/reports/released-money/generate.en.md
  guides/additional-content/reports/released-money/generate.es.md
  guides/additional-content/reports/released-money/generate.pt.md
  guides/additional-content/reports/released-money/glossary.en.md
  guides/additional-content/reports/released-money/glossary.es.md
  guides/additional-content/reports/released-money/glossary.pt.md
  guides/additional-content/reports/released-money/how-to-use.en.md
  guides/additional-content/reports/released-money/how-to-use.es.md
  guides/additional-content/reports/released-money/how-to-use.pt.md
  guides/additional-content/reports/released-money/introduction.en.md
  guides/additional-content/reports/released-money/introduction.es.md
  guides/additional-content/reports/released-money/introduction.pt.md
  guides/additional-content/reports/released-money/panel.en.md
  guides/additional-content/reports/released-money/panel.es.md
  guides/additional-content/reports/released-money/panel.pt.md
Labels: changemenu
