Repository mercadopago/devsite-docs, pull requests merged in 2023-07, with the labels that each got.

#2080 Fix/bugs-0407
  guides/additional-content/reports/released-money/generate.en.md
  guides/additional-content/reports/released-money/generate.es.md
  guides/additional-content/reports/released-money/generate.pt.md
  guides/checkout-bricks/wallet-brick/introduction.en.md
  guides/checkout-bricks/wallet-brick/introduction.es.md
  guides/checkout-bricks/wallet-brick/introduction.pt.md
Labels: bug

#2082 fix/chargeback api id parameter description update
  reference/api/chargebacks.yaml
Labels: Ready to merge

#2083 Fix/bugs-0607
  guides/additional-content/reports/released-money/glossary.en.md
  guides/additional-content/reports/released-money/glossary.es.md
  guides/additional-content/reports/released-money/glossary.pt.md
  guides/additional-content/your-integrations/introduction.en.md
  guides/additional-content/your-integrations/introduction.es.md
  guides/additional-content/your-integrations/introduction.pt.md
  guides/additional-content/your-integrations/notifications.en.md
  guides/additional-content/your-integrations/notifications.es.md
  guides/additional-content/your-integrations/notifications.pt.md
  guides/additional-content/your-integrations/webhooks.es.md
  guides/additional-content/your-integrations/webhooks.pt.md
  guides/integration-api/notifications.en.md
  guides/integration-api/notifications.es.md
  guides/integration-api/notifications.pt.md
Labels: bug

#2085 fix/mp elivery parameter description
  guides/checkout-bricks/card-payment-brick/default-rendering.en.md
  guides/checkout-bricks/card-payment-brick/default-rendering.es.md
  guides/checkout-bricks/card-payment-brick/default-rendering.pt.md
  guides/checkout-bricks/payment-brick/default-rendering.en.md
  guides/checkout-bricks/payment-brick/default-rendering.es.md
  guides/checkout-bricks/payment-brick/default-rendering.pt.md
  guides/checkout-bricks/status-screen-brick/default-rendering.en.md
  guides/checkout-bricks/status-screen-brick/default-rendering.es.md
  guides/checkout-bricks/status-screen-brick/default-rendering.pt.md
  guides/checkout-bricks/wallet-brick/default-rendering.en.md
  guides/checkout-bricks/wallet-brick/default-rendering.es.md
  guides/checkout-bricks/wallet-brick/default-rendering.pt.md
  guides/subscriptions/preapproval.en.md
  guides/subscriptions/preapproval.es.md
  reference/api/mp_delivery.yaml
Labels: Ready to merge

#2089 fix/payments api new error messages
  reference/api/payments.yaml
Labels: Ready to merge

#2094 fix/point-payment-intent-status
  guides/integration-api/create-payment-intent.en.md
  guides/integration-api/create-payment-intent.es.md
  guides/integration-api/create-payment-intent.pt.md
  guides/integration-api/glossary.en.md
  guides/integration-api/glossary.es.md
  guides/integration-api/glossary.pt.md
  guides/integration-api/notifications.en.md
  guides/integration-api/notifications.es.md
  guides/integration-api/notifications.pt.md
Labels: Don't merge

#2028 Corrección wordings glosario reportes de conciliación.
  guides/additional-content/reports/account-money/glossary.en.md
  guides/additional-content/reports/account-money/glossary.es.md
  guides/additional-content/reports/account-money/glossary.pt.md
  guides/additional-content/reports/released-money/glossary.en.md
  guides/additional-content/reports/released-money/glossary.es.md
  guides/additional-content/reports/released-money/glossary.pt.md
Labels: Ready to merge

#2103 Feature/mpdelivery catalogo
  guides/mp-delivery/accept-order.en.md
  guides/mp-delivery/accept-order.es.md
  guides/mp-delivery/accept-order.pt.md
  guides/mp-delivery/cancel-order.en.md
  guides/mp-delivery/cancel-order.es.md
  guides/mp-delivery/cancel-order.pt.md
  guides/mp-delivery/catalog-management.en.md
  guides/mp-delivery/catalog-management.es.md
  guides/mp-delivery/catalog-management.pt.md
  guides/mp-delivery/change-store-external-id.en.md
  guides/mp-delivery/change-store-external-id.es.md
  guides/mp-delivery/change-store-external-id.pt.md
  guides/mp-delivery/change-store-status.en.md
  guides/mp-delivery/change-store-status.es.md
  guides/mp-delivery/change-store-status.pt.md
  guides/mp-delivery/check-publication.en.md
  guides/mp-delivery/check-publication.es.md
  guides/mp-delivery/check-publication.pt.md
  guides/mp-delivery/get-order-data.en.md
  guides/mp-delivery/get-order-data.es.md
  guides/mp-delivery/get-order-data.pt.md
  guides/mp-delivery/import-catalog.en.md
  guides/mp-delivery/import-catalog.es.md
  guides/mp-delivery/import-catalog.pt.md
  guides/mp-delivery/integration.en.md
  guides/mp-delivery/integration.es.md
  guides/mp-delivery/integration.pt.md
  guides/mp-delivery/item-update.en.md
  guides/mp-delivery/item-update.es.md
  guides/mp-delivery/item-update.pt.md
  guides/mp-delivery/print-order-receipt.en.md
  guides/mp-delivery/print-order-receipt.es.md
  guides/mp-delivery/print-order-receipt.pt.md
  guides/mp-delivery/store-data.en.md
  guides/mp-delivery/store-data.es.md
  guides/mp-delivery/store-data.pt.md
  reference/api/mp_delivery.yaml
Labels: Ready to merge, changemenu
