Repository mercadopago/devsite-docs, pull requests merged in 2023-09, with the labels that each got.

#2122 fix/cho api doc improvements
  guides/checkout-api-v2/add-new-cards-to-customer.en.md
  guides/checkout-api-v2/add-new-cards-to-customer.es.md
  guides/checkout-api-v2/add-new-cards-to-customer.pt.md
Labels: Don't merge, draft

#2134 Revisão dos meios e tipos de pagamento
  guides/additional-content/sales-processing/payment-methods.en.md
  guides/additional-content/sales-processing/payment-methods.es.md
  guides/additional-content/sales-processing/payment-methods.pt.md
  guides/checkout-api-v2/landing.en.md
  guides/checkout-api-v2/landing.es.md
  guides/checkout-api-v2/landing.pt.md
  guides/checkout-api-v2/types-of-integration.en.md
  guides/checkout-api-v2/types-of-integration.es.md
  guides/checkout-api-v2/types-of-integration.pt.md
  guides/checkout-bricks/landing.en.md
  guides/checkout-bricks/landing.es.md
  guides/checkout-bricks/landing.pt.md
  guides/checkout-pro/landing.en.md
  guides/checkout-pro/landing.es.md
  guides/checkout-pro/landing.pt.md
  guides/subscriptions/landing.en.md
  guides/subscriptions/landing.es.md
  guides/subscriptions/landing.pt.md
Labels: Don't merge

#2072 Relatório de vendas do Marketplace do Mercado Pago
  guides/additional-content/reports/marketplace-sales/deactivation.en.md
  guides/additional-content/reports/marketplace-sales/deactivation.es.md
  guides/additional-content/reports/marketplace-sales/deactivation.pt.md
  guides/additional-content/reports/marketplace-sales/download-report.en.md
  guides/additional-content/reports/marketplace-sales/download-report.es.md
  guides/additional-content/reports/marketplace-sales/download-report.pt.md
  guides/additional-content/reports/marketplace-sales/generate.en.md
  guides/additional-content/reports/marketplace-sales/generate.es.md
  guides/additional-content/reports/marketplace-sales/generate.pt.md
  guides/additional-content/reports/marketplace-sales/glossary.en.md
  guides/additional-content/reports/marketplace-sales/glossary.es.md
  guides/additional-content/reports/marketplace-sales/glossary.pt.md
  guides/additional-content/reports/marketplace-sales/how-to-use.en.md
  guides/additional-content/reports/marketplace-sales/how-to-use.es.md
  guides/additional-content/reports/marketplace-sales/how-to-use.pt.md
  guides/additional-content/reports/marketplace-sales/introduction.en.md
  guides/additional-content/reports/marketplace-sales/introduction.es.md
  guides/additional-content/reports/marketplace-sales/introduction.pt.md
  guides/additional-content/reports/marketplace-sales/modifications.en.md
  guides/additional-content/reports/marketplace-sales/modifications.es.md
  guides/additional-content/reports/marketplace-sales/modifications.pt.md
  guides/additional-content/reports/marketplace-sales/queries-and-validations.en.md
  guides/additional-content/reports/marketplace-sales/queries-and-validations.es.md
  guides/additional-content/reports/marketplace-sales/queries-and-validations.pt.md
  images/manage-account/reports/marketplace-sales/image1.png
  images/manage-account/reports/marketplace-sales/image1pt.png
  images/manage-account/reports/marketplace-sales/image2.png
  images/manage-account/reports/marketplace-sales/image3.png
  images/manage-account/reports/marketplace-sales/image4.png
Labels: changemenu

#2161 Declaração de Privacidade para o Programa de Partners do Mercado Livre
  guides/additional-content/resources/legal/privacy-policy-platforms.es.md
  guides/additional-content/resources/legal/privacy-policy-platforms.pt.md
  guides/additional-content/resources/legal/terms-and-conditions-agencies.es.md
  guides/additional-content/resources/legal/terms-and-conditions-agencies.pt.md
Labels: changemenu
