Repository mercadopago/devsite-docs, pull requests merged in 2024-03, with the labels that each got.

#2304 feature/qr-test-doc
  guides/qr-code/LEGACY/LEGACY-qr-attended-events-to-validate.en.md
  guides/qr-code/LEGACY/LEGACY-qr-attended-events-to-validate.es.md
  guides/qr-code/LEGACY/LEGACY-qr-attended-events-to-validate.pt.md
  guides/qr-code/LEGACY/LEGACY-qr-dynamic-events-to-validate.en.md
  guides/qr-code/LEGACY/LEGACY-qr-dynamic-events-to-validate.es.md
  guides/qr-code/LEGACY/LEGACY-qr-dynamic-events-to-validate.pt.md
  guides/qr-code/qr-attended-test-purchase.en.md
  guides/qr-code/qr-attended-test-purchase.es.md
  guides/qr-code/qr-attended-test-purchase.pt.md
  guides/qr-code/qr-dynamic-test-purchase.en.md
  guides/qr-code/qr-dynamic-test-purchase.es.md
  guides/qr-code/qr-dynamic-test-purchase.pt.md
  guides/qr-code/qr-goto-production.en.md
  guides/qr-code/qr-goto-production.es.md
  guides/qr-code/qr-goto-production.pt.md
  guides/qr-code/qr-integration-test.en.md
  guides/qr-code/qr-integration-test.es.md
  guides/qr-code/qr-integration-test.pt.md
  images/qr/homologacion-qr-es.png
  images/qr/homologacion-qr-pt.png
Labels: menu modifications

#2319 fix/zda-image
  guides/zero-dollar-auth/landing.es.md
  images/zero-dollar-auth/Fluxo_ZDA_ES_Corrigido.png
  images/zero-dollar-auth/Fluxo_ZDA_ES_v3.png
Labels: Ready to merge

#2307 Inclusões e alterações em Adobe
  guides/additional-content/security/3ds.en.md
  guides/additional-content/security/3ds.es.md
  guides/additional-content/security/3ds.pt.md
  guides/adobe-commerce/cho-api-pix.en.md
  guides/adobe-commerce/cho-api-pix.es.md
  guides/adobe-commerce/cho-api-pix.pt.md
  guides/adobe-commerce/installation-composer.en.md
  guides/adobe-commerce/installation-composer.es.md
  guides/adobe-commerce/installation-composer.pt.md
  guides/adobe-commerce/installation-ftp.en.md
  guides/adobe-commerce/installation-ftp.es.md
  guides/adobe-commerce/installation-ftp.pt.md
  guides/adobe-commerce/installation-magento-marketplace.en.md
  guides/adobe-commerce/installation-magento-marketplace.es.md
  guides/adobe-commerce/installation-magento-marketplace.pt.md
  guides/adobe-commerce/installation.en.md
  guides/adobe-commerce/installation.es.md
  guides/adobe-commerce/installation.pt.md
  guides/adobe-commerce/integration-configuration.en.md
  guides/adobe-commerce/integration-configuration.es.md
  guides/adobe-commerce/integration-configuration.pt.md
  guides/adobe-commerce/landing.en.md
  guides/adobe-commerce/landing.es.md
  guides/adobe-commerce/landing.pt.md
  guides/adobe-commerce/payment-configuration.en.md
  guides/adobe-commerce/payment-configuration.es.md
  guides/adobe-commerce/payment-configuration.pt.md
  guides/adobe-commerce/prerequisites.en.md
  guides/adobe-commerce/prerequisites.es.md
  guides/adobe-commerce/prerequisites.pt.md
  guides/adobe-commerce/upgrade-to-the-new-plugin.en.md
  guides/adobe-commerce/upgrade-to-the-new-plugin.es.md
  guides/adobe-commerce/upgrade-to-the-new-plugin.pt.md
  guides/adobe-commerce/upgrade-to-the-new-version.en.md
  guides/adobe-commerce/upgrade-to-the-new-version.es.md
  guides/adobe-commerce/upgrade-to-the-new-version.pt.md
  guides/checkout-api-v2/payment-management.en.md
  guides/checkout-api-v2/payment-management.es.md
  guides/checkout-api-v2/payment-management.pt.md
  guides/checkout-bricks/payment-management.en.md
  guides/checkout-bricks/payment-management.es.md
  guides/checkout-bricks/payment-management.pt.md
  images/adobe-commerce/adb-commerce-landing.png
Labels: changemenu
